import { Router } from "express";
import nodemailer from "nodemailer";
import dns from "node:dns";

// Force IPv4 to avoid Railway ESOCKET IPv6 errors with Gmail SMTP
dns.setDefaultResultOrder("ipv4first");

const router = Router();

router.post("/send", async (req, res) => {
  try {
    const {
      to,
      subject,
      body,
      pdfBase64,
      pdfFilename,
      senderEmail,
      appPassword,
    } = req.body as {
      to: string | string[];
      subject: string;
      body: string;
      pdfBase64?: string;
      pdfFilename?: string;
      senderEmail: string;
      appPassword: string;
    };

    if (!senderEmail || !appPassword) {
      res.status(400).json({ success: false, error: "Missing sender credentials" });
      return;
    }

    const cleanPassword = appPassword.replace(/\s+/g, "");

    const transporter = nodemailer.createTransport({
      service: "gmail",
      host: "smtp.gmail.com",
      port: 465,
      secure: true,
      auth: {
        user: senderEmail,
        pass: cleanPassword,
      },
    });

    const recipients = Array.isArray(to) ? to.join(",") : to;

    const mailOptions: nodemailer.SendMailOptions = {
      from: `Maha Laxmi Transport Co. <${senderEmail}>`,
      to: recipients,
      subject,
      text: body,
      html: `<div style="font-family:Arial,sans-serif;color:#333;padding:16px;">
        <h2 style="color:#B8872A;">Maha Laxmi Transport Co.</h2>
        <p>${body.replace(/\n/g, "<br>")}</p>
        <hr style="border-color:#e0d4b4;margin:16px 0;">
        <p style="font-size:12px;color:#888;">Generated by LR Generator App</p>
      </div>`,
    };

    if (pdfBase64 && pdfFilename) {
      mailOptions.attachments = [
        {
          filename: pdfFilename,
          content: pdfBase64,
          encoding: "base64",
          contentType: "application/pdf",
        },
      ];
    }

    await transporter.sendMail(mailOptions);
    res.json({ success: true });
  } catch (error) {
    req.log.error({ error }, "Failed to send email");
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : String(error),
    });
  }
});

export default router;
