kind = "mobile"
previewPath = "/"
title = "LR Generator"
version = "1.0.0"
id = "artifacts/lr-generator"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25483

[services.development]
run = "pnpm --filter @workspace/lr-generator run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lr-generator", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/lr-generator", "run", "serve" ]

[services.env]
PORT = "25483"
BASE_PATH = "/"
